### ISSUE TITLE
How do i have the titles of CEWP's on Publishing pages carried over to modern?

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#120]
[ ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[x] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Content editor webparts on classic pages have the title set in the webpart properties and the  Chrome Type set to Title Only:
![image](https://user-images.githubusercontent.com/2412956/56087116-838de100-5e32-11e9-91ba-64f551c705a8.png)

Webpart  title should be displayed after page is migrated.

#### Observed Behavior

webpart title is not displayed after webpart is migrated.

On old publishing page I have this:
![image](https://user-images.githubusercontent.com/2412956/56087144-f5662a80-5e32-11e9-8f0d-9ec4acf0d328.png)

After Migration it is this:
![image](https://user-images.githubusercontent.com/2412956/56087150-1cbcf780-5e33-11e9-964c-ed80035bc2a5.png)

I'm using the oob webpart mappings

**Comment by jansenbe** [comment]
Let me investigate this one first

**Comment by jansenbe** [comment]
Based on a quick look we can use the ChromeType parameter to check if the web part is configured to show a title or not. Makes sense to take this in account as then the content better matches with was on screen on the classic page.

**Comment by jansenbe** [comment]
Fixed in https://github.com/SharePoint/sp-dev-modernization/commit/19a48357aff914ae2b62445075851e2da1666fd7.

**Comment by russgove** [comment]
Hi Bert, I downloaded the latest sp-dev-modernization  and reran with the
latest bits, but I still dont see the title.
Stepping thouhg the code you added I see that wp.Properties has no
'ChromeType' property.  But its definitely set on the webpage.
[image: image.png]

Am i missing something?

**Comment by russgove** [comment]
Ah, I see ... I needed to add the ChromeType to the webpart mapping file. Working great now!

**Comment by russgove** [comment]
Same issue with summary links webpart. I'll open a new issue.
