### ISSUE TITLE
ConvertTo-PnPClientSidePage : Field or property "ExportMode" does not exist.

### ISSUE THREAD

**Issue by AAnkitaAswal** [SharePoint/sp-dev-modernization#251]
Command: ConvertTo-PnPClientSidePage -Identity "Ankita13.aspx" -PublishingPage -TargetConnection $target -Overwrite-PageLayoutMapping  "C:\QianetMig\Prod\pagelayoutmapping.xml" –AddPageAcceptBanner

Error: ConvertTo-PnPClientSidePage : Field or property "ExportMode" does not exist.

**Comment by jansenbe** [comment]
Hi @AAnkitaAswal,

This issue has been fixed in the dev release and will be part of the upcoming September release. I assume you're trying to migrate publishing pages from 2013/2016 on-premises to SPO and those pages have web parts on them?

**Comment by AAnkitaAswal** [comment]
> Hi @AAnkitaAswal,
> 
> This issue has been fixed in the dev release and will be part of the upcoming September release. I assume you're trying to migrate publishing pages from 2013/2016 on-premises to SPO and those pages have web parts on them?

Hi Jasenbe,

Yes, we are trying to migrate pages from SP2013 to SPO and these pages do have custom (VS) webparts as well...
so this will be available for all in Sep release.

**Comment by jansenbe** [comment]
Correct. Alternatively you can build your own version of the modernization framework and PnP PS, but September release will be out in about 2 weeks.

**Comment by jansenbe** [comment]
closing the issue now. If you still have issues with the September release then please open a new issue.

**Comment by AAnkitaAswal** [comment]
Hi Bert,

Just to touch base, if the functionality to migrate publishing pages from on prem server to online modern pages is now available through pnp.

Regards,
Ankita Aswal

**Comment by jansenbe** [comment]
@AAnkitaAswal , yes it is but would recommend waiting for the October release as we've fixed one other related bug for this scenario. The October release will be available on Monday October 7th.

**Comment by AAnkitaAswal** [comment]
Hi Jarsen,

I am still facing same issue:
[cid:image001.png@01D57E85.42001730]
I had updated PNP powershell online.


Regards,
Ankita Aswal

**Comment by pkbullock** [comment]
Hi @AAnkitaAswal the screenshot didn’t upload, can you try again. Also if you get an error and the logs, we made some tweaks to those to get more info about the types of transforms. Thanks.

**Comment by AAnkitaAswal** [comment]
Hi Paul,

Here is the error message-

PS C:\QianetMig> Update-Module SharePointPnPPowerShell*

PS C:\QianetMig> C:\QianetMig\ConvertPage.ps1
ConvertTo-PnPClientSidePage : Field or property "ExportMode" does not exist.
At C:\QianetMig\ConvertPage.ps1:21 char:1
+ ConvertTo-PnPClientSidePage -Identity "AnkitaTest1.aspx" -PublishingP ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage

PS C:\QianetMig>


Regards,
Ankita Aswal

**Comment by jansenbe** [comment]
Hi @AAnkitaAswal ,

Please run the transformation cmdlet with logging (add this: `-LogType File -LogVerbose -LogFolder "c:\temp"`) and then provide us with the generated report. When you look at the page that fails, where are the custom web parts inserted? In a web part zone or in a field? Also remove the -PageAcceptBanner as that feature will not work for publishing pages.

**Comment by AAnkitaAswal** [comment]
Hi Jansen,

I have attached report,
Yes page has a content webpart added in the topmost webpart zone.

We havenot added -PageAcceptBanner in the script.

It worked, if there is not webpart in source page.

Regards,
Ankita Aswal

**Comment by jansenbe** [comment]
Hi @AAnkitaAswal ,

Answering on this via mail will drop the attachments...can you go to the issue in git (https://github.com/SharePoint/sp-dev-modernization/issues/251) and add the attachments over there?

**Comment by AAnkitaAswal** [comment]
[Page-Transformation-Report-10-10-2019-8-48-49-AM.txt](https://github.com/SharePoint/sp-dev-modernization/files/3710911/Page-Transformation-Report-10-10-2019-8-48-49-AM.txt)

**Comment by jansenbe** [comment]
The October version log file will show the version numbers, your log does not...this means you're still using an older version. Can you try to upgrade pnp-powershell to the latest release (October version, 3.14.1910.0).

Running `get-module *pnp*` should show the version you've currently loaded.

**Comment by jansenbe** [comment]
So you should be all good then. Closing this issue.
