### ISSUE TITLE
Content Editor web parts not transforming

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#53]
#### Category

[X] Bug
[] Enhancement

#### Problem Area

[ ] Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Error during the use of page transformation from PnP PowerShell
[ ] Error during the use of page transformation from .Net
[X] Page is not looking correct after transformation

#### Expected or Desired Behavior

Content Editor Web Parts are included in the transformation

#### Observed Behaviour

Content Editor Web Parts are not transforming to Text Web Parts, when using the ConvertTo-PnPClientSidePage cmdlet

In the text scenario, I have a summary links web part on the page also.

#### Steps to Reproduce

Create classic publishing site
Enable the features for Site Pages
Create a web part page and added multiple Content Editor web parts with text
Run the cmdlet

New page is created with sections but no text web parts.

#### Submission Guidelines

Message          : Unable to find repository 'Name'. Use Get-PSRepository to see all available repositories.
Stacktrace       :
ScriptLineNumber : 4489

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     3.5.1901.0 SharePointPnPPowerShellOnline       {Add-PnPApp, Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText...}

**Comment by jansenbe** [comment]
Hey @pkbullock,

By default only content editor web parts that point to an .aspx file are transformed using contentembed (the aspx check was added in the 1.01902 version which will be part of the February PS drop - will be available really soon now). If you want to transform script editor or content editor with embedded content then have a look at https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/modernization-ui-faq.md#my-script-editor-and-content-editor-web-parts-are-not-transformed. This shows you how to change the default webpartmapping file to transform towards the open source 3rd party script editor.

**Comment by pkbullock** [comment]
hi @jansenbe 

Thank you for getting back to me and do appreciate you help,

How about if the content editor web part just contains HTML or text entered into the web part through the UI, will the transformation tool convert this Modern Text Web Part?

I ask, because I have seen there are classes for "HtmlTransformator" in the tooling that converts html into a format the modern client text web part supports, so I'm thinking in theory that this could work or is already a function of the tool - Of course, I could be thinking of the wrong use case here.

**Comment by jansenbe** [comment]
Interesting idea...there's indeed support for html transformation which is used for all the wiki html content. When it comes to content editor the current model relies on the 3rd party script editor web part to handle the html as the html content could be mixed with script. In your proposal we would check for script inside the embedded content and if not replace by "cleaned" text, which does make sense. 

Content editor is also used to point to files...currently pointing to an aspx file does work, html files however don't. Having an option to read the contents of the html file and transform it as text might be a nice option as well. What do you think? Do you see a lot of content editor usage for non script html content?

**Comment by pkbullock** [comment]
Hi @jansenbe 

The content editor could have a few usage scenarios:

- Linked Content to a file (already a feature of the tool to transform)
- Embedded content - Just JavaScript and CSS content
- Embedded content - HTML Content with script and CSS 
- Embedded content - Just HTML Content

So for the Intranet project I am working on - I wrote a script to collect some metrics (just needed to tweak to provide context), the customer has an Intranet that contains approximately 9100+ content editor web parts alone e.g. multiples per page.  154 of those contained script or style tags, 2030 contained references to external files and the rest from sampling the content is just regular HTML.

So this project uses all the above scenarios

**Comment by jansenbe** [comment]
So the current intranet is build using wiki and web part pages I assume...publishing pages are (currently) not supported. I'll flag this issue as enhancement and will do some prototyping on a solution. When the embedded content contains JS or CSS the only reliable approach is using the third party script editor, but as mentioned for the other scenarios this would result in a solution without depending on the third party script editor.

**Comment by pkbullock** [comment]
The intranet is a publishing site. 

To workaround this issue, I have activated the Site Pages feature on the publishing site, add the Web Part Page content type and I wrote a PowerShell script to export the web parts from publishing page, import into a new WebPart Page, the run the ConvertTo-PnPClientPage which works and transforms (except for the above).  I am still investigating a better approach, its way too hacky.

Paul

**Comment by jansenbe** [comment]
Implemented improved content editor support following below logic:

If a link was used then:
- When aspx => OOB content embed
- When other (html): read file contents and
  - When no embedded script: OOB text (after conversion) -OR- 3rd party modern script editor
  - When embedded script: OOB error message -OR- 3rd party modern script editor

If content was embedded in the web part:
- When no embedded script: OOB text (after conversion) -OR- 3rd party modern script editor
- When embedded script: OOB error message -OR- 3rd party modern script editor

**Comment by jansenbe** [comment]
Hi @pkbullock,

I've implemented above model, can you give it a try on your pages and see how that works. It now does a "best effort" approach when there's no 3rd party script editor by replacing by text if either the embedded content or the referenced file does not contain script. Obviously you can edit the mapping file to use the 3rd party script editor in all cases. 

Note: did not add a check on CSS usage, but possible the test for script (BuiltIn.ContainsScript) could be extended to also check for style references.

**Comment by jansenbe** [comment]
Closing this one for now, feel free to open a new one when needed.

**Comment by jonyfang2018** [comment]
Hi, I am still having problem converting content editor webpart to modern page on SPO. The webpartmapping.xml ( https://github.com/SharePoint/sp-dev-modernization/blob/master/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework/Nuget/webpartmapping.xml) has all the line un-commented. Is there anything else I should change?

**Comment by pkbullock** [comment]
Hi @jonyfang2018 can you open a new issue? this one is v old. You shouldn't need to use any mapping file for content editor web parts to work? in the new issue, can you describe what the issue is exactly, use the logging options in PS if thats the mechanism, what type of transform?
